### ISSUE TITLE
Doctestのやり方について

### ISSUE THREAD

**Issue by youyou-ku** [sotetsuk/python-dev-tutorial#45]
Doctestのやり方が分からず困ったので、Doctestを実行する際のプログラムに対しても記述が欲しいです

**Comment by youyou-ku** [comment]
場所は　#7 です。
if __name__ == '__main__':
    import doctest
    doctest.testmod()
が必要なことと、defの中に
'''
>>>fuzzbuzz(3)
'Fuzz'
'''
などと入れることでDoctestが実行できる、くらいの説明を追記していただけるとありがたいです

**Comment by sotetsuk** [comment]
```py
if name == 'main':
import doctest
doctest.testmod()
```

は多分PyCharm使ってる文には必要ないはずなんですけどね 🤔 
後半は承知しました 👍

**Comment by sotetsuk** [comment]
解説を追加しました！
